Update update.yml

diff --git a/.github/workflows/update.yml b/.github/workflows/update.yml
--- a/.github/workflows/update.yml
+++ b/.github/workflows/update.yml
@@ -16,13 +16,31 @@ jobs:
 
     steps:
     - uses: actions/checkout@v4
+    - name: Install jq
+      run: sudo apt-get update && sudo apt-get install -y jq
+    - name: Fetch latest sing-box release
+      id: fetch-release
+      run: |
+        # Fetch the latest release data
+        LATEST_RELEASE=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest)
+        # Extract the download URL for the Linux amd64 .deb package
+        SING_BOX_DEB_URL=$(echo $LATEST_RELEASE | jq -r '.assets[] | select(.name | endswith("linux_amd64.deb")) | .browser_download_url')
+        # Check if the URL is empty
+        if [ -z "$SING_BOX_DEB_URL" ]; then
+          echo "Latest sing-box .deb package not found."
+          exit 1
+        fi
+        # Set the output for use in other steps
+        echo "::set-output name=deb_url::$SING_BOX_DEB_URL"
     - name: "Setup sing-box"
       env:
-        SING_BOX_DEB_URL: "https://github.com/SagerNet/sing-box/releases/download/v1.10.7/sing-box_1.10.7_linux_amd64.deb"
+        SING_BOX_DEB_URL: ${{ steps.fetch-release.outputs.deb_url }}
       run: |
-          set -Eeuo pipefail
-          wget -O sing-box.deb $SING_BOX_DEB_URL
-          sudo dpkg -i sing-box.deb
+        set -Eeuo pipefail
+        wget -O sing-box.deb "$SING_BOX_DEB_URL"
+        sudo dpkg -i sing-box.deb
+        rm sing-box.deb
+
     - name: Set up Python3
       uses: actions/setup-python@v5
       with:
